### ISSUE TITLE
Syntax error on Guix with OpenJDK

### ISSUE THREAD

**Issue by igajsin** [clojure-emacs/orchard#152]
Hi. First of all thanks for the cider, it's awesome. But there is a problme when using it on guix linux with openjdk. When I do `cider-jack-in` I receive an error: https://paste.debian.net/1231025/

There is another issue with that problem unfortunately I don't have enouhg experience to understand the answer https://github.com/clojure-emacs/orchard/issues/117#issuecomment-859987280

Please, help me to assemble pieces of that puzzle together:

1. Someone (leiningen?) going to compile orchard, but 
```Syntax error compiling at (cider/nrepl/inlined_deps/orchard/v0v6v5/orchard/java/parser.clj:1:1).```

2. In the another issue there is the recomendation: 

> use ONLY the package "openjdk:jdk".

It's kind of a fragment a defintion in a guix's package description

3. I've got from another confersation

> Openjdk has two outputs: out and jdk. The default output contains only
what's necessary to *run* a Java application, while the jdk output
contains that *in addition* to what's needed to build Java applications
(javac, ...). 

4. all together: when emacs-cider starts, it commands to a program to compile orchard, but the program was defined and built with wrong openjdk-output, and it can't build what it should and failed.

5. Is it correct? If so, what is the program that I need to fix?

**Comment by vemv** [comment]
Thanks!

The stacktrace might be readily available in the `*cider-error*` buffer.

If you still have trouble getting a full stacktrace, you might have better luck by launching a repl with cider in it from the terminal:

* Follow https://docs.cider.mx/cider/basics/middleware_setup.html#using-leiningen
* simply launch `lein repl`
* check if any error pops up immediately
* if not, you can then use `cider-connect` from Emacs, connecting to this existing repl process.

---

> it works well, so I believe the problem isn't on the cider side.

From what I can see, one is Java 8 and the other is Java 17. Both are different enough that we can't be sure yet of what the issue is.

**Comment by igajsin** [comment]
here is a stacktrace [lein.log](https://github.com/clojure-emacs/orchard/files/8074170/lein.log) is it what are you looking for?

**Comment by vemv** [comment]
Yes, thanks much!

Can you confirm that in a vanilla `lein repl` (without any plugin), the following fails...?

```clj
(import 'jdk.javadoc.doclet.Doclet)
```

**Comment by igajsin** [comment]
When I run `lein repl` I receive the almost equal stacktrace. Then I removed `[cider/cider-nrepl "0.25.9"]` from `~/.lein/profiles.clj` and managed to run the command
```/tmp/tmp.6SkhGYoWd3$ lein repl
Warning: refactor-nrepl needs to run in the context of a project.
Warning: refactor-nrepl middleware won't be activated.
nREPL server started on port 41293 on host 127.0.0.1 - nrepl://127.0.0.1:41293
REPL-y 0.5.1, nREPL 0.8.3
Clojure 1.10.3
OpenJDK 64-Bit Server VM 17.0.1+0-adhoc..source
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (import 'jdk.javadoc.doclet.Doclet)
Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (REPL:-1).
jdk.javadoc.doclet.Doclet
```

**Comment by vemv** [comment]
So, yes, that confirms our suspicion that your JDK doesn't include all classes that we would expect.

Generally we consider `jdk.javadoc.doclet.Doclet` a part of the JDK, and if it's missing, that's because a specific Linux distro decided to split the JDK in some manner.

That's outside of what we can directly fix.

My suggested fix would be to:

* determine which specific Guix package installed JDK17
* find a complementary, closely-related package that includes additional classes
  * surely Guix has some package search engine / feature?
* install it

Hope it goes nicely!

**Comment by igajsin** [comment]
Thanks a lot. After the problem is pinpointed the solution is quite obvious. So, for those who'll google the issue:

1. Guix support multiple outputs for a single package https://guix.gnu.org/manual/en/html_node/Packages-with-Multiple-Outputs.html
2. The openjdk package has 3 outputs: out (default, has only necessary to run things), jdk (also things for development) and doc (documentation). Therefore to make it run one need to install openjdk as
```
guix package -i openjdk:jdk
```
and it works.

**Comment by vemv** [comment]
Cheers 🍻

We'll consider reflecting this tip on the CIDER docs (@bbatsov )
