### ISSUE TITLE
Generate some API documentation automatically

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/orchard#18]
I guess we should help people figure out how to use our library.

@gonewest818 Can you help with this?

**Comment by gonewest818** [comment]
Sure. Is there a preference in terms of tool? Codox or marginalia or ...

**Comment by bbatsov** [comment]
Codox will do fine IMO, but if you have better ideas - I'm open to hearing them.

**Comment by gonewest818** [comment]
Codox is fine with me.

**Comment by gonewest818** [comment]
I'm working on this in a separate repo to get all the mechanics worked out in my head. The core idea is exactly what @xiongtx [posted to the codox wiki](https://github.com/weavejester/codox/wiki/Deploying-to-GitHub-Pages), but for purposes of CI automation I'm experimenting with checking out the codox files as a git submodule.  I've never seen this before (where the submodule is actually the same project checked out to a different branch, i.e. the `gh-pages` orphan branch). However `git` seems not to care what the submodule is.

**Comment by gonewest818** [comment]
Reopening this ticket. The auto-publishing script is broken, and I'm looking at the upstream project as well as adjusting things here.

**Comment by gonewest818** [comment]
@bbatsov can you go into the orchard project settings to confirm GitHub Pages is enabled and configured to serve from the "gh-pages" branch?

<img width="767" alt="screen shot 2018-03-05 at 10 36 44 pm" src="https://user-images.githubusercontent.com/2460918/37017588-04770b12-20c6-11e8-945e-8874e5c46d72.png">

**Comment by bbatsov** [comment]
![image](https://user-images.githubusercontent.com/103882/37018019-62218aec-2145-11e8-9098-4430a1709fd6.png)

Done.

**Comment by gonewest818** [comment]
I can't see why the page isn't visible. You should get a simple index here
http://clojure-emacs.github.io/orchard/
http://clojure-emacs.github.io/orchard/index.html

and the current docs for master here
http://clojure-emacs.github.io/orchard/master/
http://clojure-emacs.github.io/orchard/master/index.html

I set up a test project here https://gonewest818.github.io/codox-experiment/index.html and it all seems to be working as expected.

GitHub community forums say things like "try deleting and recreating the gh-pages" branch (I did), or "push another commit to the branch and wait" (I did), or turn off the GitHub Pages publishing in the settings and wait 30 minutes before turning back on (and this I can't do because I can't access the settings @bbatsov).

**Comment by bbatsov** [comment]
I can't see anything. I just gave you admin access to the repo, so I guess you should see all the settings .

**Comment by gonewest818** [comment]
Ok. And I just emailed GitHub support. I figure why not, I’m paying for it.

**Comment by gonewest818** [comment]
Closing.  I deleted and regenerated the gh-pages branch one more time, and no rhyme or reason, but this time the publish seems to work.
