### ISSUE TITLE
javadoc url resolving is broken for java10

### ISSUE THREAD

**Issue by finalpatch** [clojure-emacs/orchard#31]
## Expected behavior

Can show java class method doc in Emacs buffer
Can jump to java class method doc in browser

## Actual behavior

cider-doc emacs buffer shows

```
Not documented.

For additional documentation, see the Javadoc.

Definition location unavailable.
```

Click Javadoc link or use "C-c C-d j" only opens class doc in browser but doesn't jump to the method.

## Steps to reproduce the problem

"C-c C-d d" then type ".toUpperCase"
or
"C-c C-d j" then type ".toUpperCase"

## Environment & Version information

;; CIDER 0.18.1snapshot (package: 20180929.818), nREPL 0.4.5

### Clojure version

1.9.0

### Java version

OpenJDK 10

If I run with openjdk9 then browser can directly jump to method.  Apparently the URLs are slightly different in Java10 (java9 doc uses - as separator but 10 uses '()')

cider-doc doesn't work even in openjdk9

### Operating system

Windows 10 x64

**Comment by bbatsov** [comment]
@jeffvalk Can you look into this? If it's just a format change I assume that'd be pretty easy to fix.

**Comment by jeffvalk** [comment]
In orchard, this is a two part issue:
1. The URL base path changed for Java 11+. This is now accommodated in 4b60bc1.
2. Also as of Java 11, class URLs now include the module. Module info doesn't exist before JDK9, so in order to support both JDK8 and 9+, we'll have to use conditional loading. Not a huge deal (`orchard.java` already does it), but more than just changing a URL string. I'll look at it soon.

@bbatsov It looks like the `info` code that's currently running is coming from CIDER middleware, not orchard. Can you confirm?

**Comment by bbatsov** [comment]
The info middleware is just a very think wrapper around orchard. After we merge #37 it's going to be even thinner.

**Comment by jeffvalk** [comment]
For reference, Java 10+ stops munging argument types, and Java 11+ adds segments to the path of the URL.

| Java Version | URL |
|---|---|
| 8 | https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#sleep-long- |
| 9 | https://docs.oracle.com/javase/9/docs/api/java/lang/Thread.html#sleep-long- |
| 10 | https://docs.oracle.com/javase/10/docs/api/java/lang/Thread.html#sleep(long) |
| 11 | https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Thread.html#sleep(long) |
| 12 | https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Thread.html#sleep(long) |

**Comment by bbatsov** [comment]
So many recent changes! Thanks for taking care of this! 🙇
