### ISSUE TITLE
ClojureScript compatibility

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/orchard#32]
Hi all!

I was wondering how to proceed in the case I wanted to use, for instance, `spec.clj` in the context of ClojureScript code and in general how to enable, possibly port, some code over.

Is orchard going to have a layer targeting each or this is just a lib and how to use it will always need to be handled elsewhere?

Thanks a lot in advance for the answers!

**Comment by bbatsov** [comment]
Frankly, I haven't given this that much thought. I was thinking of orchard and cljs-tooling as two libraries providing more or less the same functionality for Clojure and ClojureScript. I even planned to rename cljs-tooling to orchard-cljs at some point. 

I also thought of coalescing the two libs at some point, but the problem is how to avoid the cljs dep for people won't need it. 

Ideas and suggestions are always welcome!

**Comment by arichiardi** [comment]
Oh, I like the merge actually!

I thought that the dependency on cljs is never a hard dependency, as ClojureScript is actually only used for development - to compile things down.

In my projects I never put it in the `:dependencies` and also I think I did the same in [cljs-tooling](https://github.com/clojure-emacs/cljs-tooling/blob/master/project.clj).

So I think it can be done with no issue, who compiles will add the cljs dep they desire.
Am I misinterpreting this?

**Comment by arichiardi** [comment]
Bohzidar you are far from confused I forgot we use the API there :smile:
